services:
  home-banking:
    build: ./home_banking
    ports:
      - "5005:5005"
    environment:
      - FLASK_ARGS=--host=0.0.0.0 --port=5005 --debug
      - MY_CLIENT_ID=aaaaaaaaaaaaaaaaaaaaaaaa
      - MY_CLIENT_SECRET=BkcHH9B4CX0IdrJwofdMAIf0gMoPjdykvPzINW1gPZzDxtHt
    env_file:
      - environment_variables
    networks:
      - iaa_network
  bank-managing-officer:
    build: ./bank_managing_officer
    ports:
      - "5006:5006"
    environment:
      - FLASK_ARGS=--host=0.0.0.0 --port=5006 --debug
      - MY_CLIENT_ID=bbbbbbbbbbbbbbbbbbbbbbbb
      - MY_CLIENT_SECRET=BkcHH9B4CX0IdrJwofdMAIf0gMoPjdykvPzINW1gPZzDxtHt
    env_file:
      - environment_variables
    networks:
      - iaa_network
  bank-managing-manager:
    build: ./bank_managing_manager
    ports:
      - "5007:5007"
    environment:
      - FLASK_ARGS=--host=0.0.0.0 --port=5007 --debug
      - MY_CLIENT_ID=cccccccccccccccccccccccc
      - MY_CLIENT_SECRET=BkcHH9B4CX0IdrJwofdMAIf0gMoPjdykvPzINW1gPZzDxtHt
    env_file:
      - environment_variables
    networks:
      - iaa_network

networks:
  iaa_network:
    external: true